### ISSUE TITLE
Possibility to connect to devices

### ISSUE THREAD

**Issue by onny** [t-wissmann/bluetooth-browser#1]

**Comment by t-wissmann** [comment]
What do you mean by this? In principle, it's possible to pair and connect with devices (actually, this is the only thing, `bluetooth-browser` is capable of). I know that there are exceptions from time to time that I don't understand myself entirely, but this does not seem to be the issue here, doesn't it?

**Comment by onny** [comment]
I'm only able to select the first two entries with the cursor (power and scanning). I'm unable to move down to the BT-devices using the arrow keys :(

**Comment by t-wissmann** [comment]
Does it work with <kbd>j</kbd> and <kbd>k</kbd>?

**Comment by onny** [comment]
Oh you're right, yes this works. Maybe one should support arrow keys too? Might be more intuitive.
